### PR TITLE
runebar: account for energized runes

### PR DESCRIPTION
**Pull request by Rainrider**
Fixes https://github.com/haste/oUF/issues/294

### CODE REVIEW

**Comment by Rainrider** [comment]
Other elements unregister the events of the default ui to prevent it from updating. Is it intentional that the runebar does not?

Also, the default RuneFrame has code support for up to 7 runes. Although I didn't find any DK spell that grants extra runes, wouldn't it be future-proof if the element would iterate over all user-created widgets in the Runes table rather than just the magic 6?

**Comment by p3lim** [comment]
> Also, the default RuneFrame has code support for up to 7 runes. Although I didn't find any DK spell that grants extra runes, wouldn't it be future-proof if the element would iterate over all user-created widgets in the Runes table rather than just the magic 6?

Might be something related to the artifact?

Layouts should probably be allowed to dictate the max, although it's more error-prone if they do (GetRuneCooldown throws an error for invalid indices afaik). Same with totems as you mentioned in [haste#283](https://github.com/haste/oUF/pull/283).

**Comment by Rainrider** [comment]
GetTotemInfo returns non-nils up to index 5. After that it's all nils, so no errors. Same with GetRuneCooldown, and you even already added a guard against nil returns for the runebar element. The update will also bail if the rune is not present, so no error on that side too. We could of course inform the layout user about that if this is considered the right approach.

**Comment by ls-** [comment]
Regarding 7 runes. It's a leftover from early alpha/beta, earlier some specs had 7 runes, the idea was scrapped, but UI code is still there.

**Comment by Rainrider** [comment]
Btw I placed the PR here as this branch is PR'ed in https://github.com/haste/oUF/pull/269. Please tell me if I should do it in another way.

**Comment by p3lim** [comment]
@Rainrider That is fine. Could you perhaps add the commit for letting layouts define the table size? I'm mobile right now so I can't do much else than merge.

**Pull request merged**
